### ISSUE TITLE
Dark mode for main screen

### ISSUE THREAD

**Issue by kominak** [gyim/breviar-ios#20]
Juraj:

> is it possible that one of the main settings (daily/night mode) will affect the background of main screen (where user chooses prayer)?

**Comment by breviar-sk** [comment]
It would be fine when the main screen & settings (thus whole native iOS menu) could be influenced by CSS.

**Comment by gyim** [comment]
@breviar-sk I started working on this because iOS 13 added support for dark mode, so we will have to support this in our next release. I was thinking that to simplify the implementation, we could implement this relying on the iOS API support, while keeping the current implementation for older iOS versions.

What do you think about the following implementation?

- The UI should be dark or light based on the system-wide settings. This means that only iOS 13 users can use dark mode on the main screen.
- The web views should follow system-wide settings by default. Keep the light/dark switcher as an override, but only for the web views. So iOS <13 users lose no functionality.
- In settings: instead of having a "dark mode" flag, have a "color scheme" option with 3 possible values: system default, light mode, dark mode.

Also, do you think having iOS 11 as a minimal version is enough for our purposes? It would make the implementation much easier: it has support for named colors, so we can specify a name like `BRTint`, and specify its hex value in Interface Builder based on light mode / dark mode settings.
